name: linux
on:
  push:
    branches:
      - main
jobs:
  perl:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl-version:
        - '5.36'
    container:
      image: perl:${{matrix.perl-version}}
    steps:
    - uses: actions/checkout@v3
    - name: perl -V
      run: perl -V
    - name: Install dependencies
      run: |
        cpanm -n EV~"!= 4.28"
        cpanm -n Test::Pod Test::Pod::Coverage
        cpanm -n --installdeps .
    - name: Run perl tests
      run: prove -l
      env:
        HARNESS_OPTIONS: j4
        TEST_POD: 1
